### ISSUE TITLE
A nil value

### ISSUE THREAD

**Issue by GreenPlantITP** [qurs/i-oldogames#25]
```
[ERROR] lua/vgui/dlistview_line.lua:100: attempt to call method 'ApplySchemeSettings' (a nil value)
  1. SetSelected - lua/vgui/dlistview_line.lua:100
   2. OnClickLine - lua/vgui/dlistview.lua:440
    3. unknown - lua/vgui/dlistview_line.lua:89
```

Данная ошибка возникает в режиме Slasher, если в TAB-меню нажать на вытянутые ячейки, с информацией о игроке.

**Comment by JaneFreeman4707** [comment]
Ошибка предоставлена в обрезанном виде. Отправь её полностью, пожалуйста.

**Comment by GreenPlantITP** [comment]
Прошу прощения, при вставке строчка оказалась в некорректном положений между апострофами, из-за чего она не отобразилась.

**Comment by JaneFreeman4707** [comment]
Проблема передана разработчику.
